name: Package Checks

on:
  push:
    branches:
      - main
      - feat/utils-setup
  pull_request:
    branches:
      - main
      - feat/utils-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
