name: main-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install latest NPM
        run: npm install -g npm@latest   

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Clear npm cache
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm config set '//npm.pkg.github.com/:username' 'check-dc-dev'

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
